export const paths = {
  start: 'start',
  internships: 'internships',
  fillForm: 'fill-form',
  finish: 'finish',
  login: 'login',
  projects: 'projects',
  candidates: 'candidates',
  profile: 'profile',
  shared: 'shared',
  fof: '404',
  index: '',
  rest: '**',
  slash: '/',
  calendar: 'calendar',
  calendarRecruiter: 'calendar-recruiter',
};
